### ISSUE TITLE
Documentation - customer oriented

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/metadefender-menlo-integration#54]
Start documenting:
- How to deploy the environment
- How to test the end to end flow
- add diagrams and videos as a reference

**Comment by MaNe2020** [comment]
@svf97 I'll start working on diagrams and videos and also add end to end testing steps.
I think you already did some part on deployment, was that merged?

**Comment by svf97** [comment]
@MaNe2020 i haven't created PR until we finalized a coherent doc
